---
- name: Finding the pre & post check result files.
  shell: (cd /home/; find . -maxdepth 1 -type f -iname "*.txt") | cut -d'/' -f2
  register: files_to_fetch

- name: Fetching the Files to Ansible Server
  fetch:
    src: /home/{{item}}
    dest: /tmp/
  with_items: 
  - "{{files_to_fetch.stdout_lines}}"
...