---
- name: Finding the pre & post check result files.
  ansible.builtin.shell: (cd /home/; find . -maxdepth 1 -type f -iname "*.txt") | cut -d'/' -f2
  register: files_to_fetch

- name: Fetching the Files to Ansible Server
  ansible.builtin.fetch:
    src: /home/{{ item }}
    dest: /tmp/
  loop: 
    - "{{ files_to_fetch.stdout_lines }}"
...