---
- name: Self Made Patching Playbook
  hosts: all
  become: true
  tasks:
    - name: Copy pre-check script to the remote server
      ansible.builtin.copy:
        src: /home/ubuntu/precheck.sh
        dest: /home/
        mode: preserve

    - name: Execute the pre-check script
      ansible.builtin.command: /home/precheck.sh    

    - name: Applying Patches
      ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Rebooting Nodes
      ansible.builtin.reboot:
        reboot_timeout: 6000

    - name: Copy post-check script to the remote server
      ansible.builtin.copy:
        src: /home/ubuntu/postcheck.sh
        dest: /home/
        mode: preserve

    - name: Execute the post-check script
      ansible.builtin.command: /home/postcheck.sh

    - name: Finding the pre & post check result files.
      ansible.builtin.shell: (cd /home/; find . -maxdepth 1 -type f -iname "*.txt") | cut -d'/' -f2
      register: files_to_fetch

    - name: Fetching the Files to Ansible Server
      ansible.builtin.fetch:
        src: /home/{{item}}
        dest: /tmp/
      loop: "{{files_to_fetch.stdout_lines}}"
...