name: ansible-lint-check
on:
  pull_request:
    branches: ["main"]
  push:
    branches: [ "main" ]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0
      - name: Running ansible-lint
        uses: ansible/ansible-lint@v6
        with:
            working_directory: "roles/"